import {apiFetch} from "../api";
import {useRef,useState} from "react";
import {parseSSEEvent} from "../utils/sse";
export function responseDetailFromPayload(data,fallback){return data?.detail||fallback}
async function responseDetail(response,fallback){try{return responseDetailFromPayload(await response.json(),fallback)}catch{return fallback}}
export function getEditableLastUser(messages){if(!messages?.length||messages.length<2)return null;const userIndex=messages.length-2,old=messages[userIndex];return old?.role==="user"?{value:old.content,index:userIndex}:null}
export default function useChat({API,chats,setChats,active,setActive,text,setText,attachments,setAttachments,loading,setLoading,notify,webSearch,memory}){
 const [streamController,setStreamController]=useState(null);const sendingRef=useRef(false);const chat=chats.find(c=>c.id===active)||chats[0];
 function normalizeMessages(messages=[]){const result=[];for(const m of messages){if(result.length&&result.at(-1)?.role===m.role&&result.at(-1)?.content===m.content)continue;result.push(m)}return result}
 function update(messages){const normalized=normalizeMessages(messages);setChats(cs=>cs.map(c=>c.id===active?{...c,messages:normalized,title:c.title==="New conversation"?(normalized.find(m=>m.role==="user")?.content||"New conversation").slice(0,32):c.title}:c))}
 async function regenerate(){if(loading||!chat?.messages?.length||chat.messages.at(-1)?.role!=="assistant")return;setLoading(true);try{const r=await apiFetch(API+"/api/v1/chats/"+encodeURIComponent(active)+"/regenerate",{method:"POST"});if(!r.ok){notify(await responseDetail(r,"Regeneration failed"));return}const d=await r.json();update([...chat.messages.slice(0,-1),{role:"assistant",content:d.answer||""}])}catch{notify("Regeneration failed")}finally{setLoading(false)}}
 function editLastUser(){return loading?null:getEditableLastUser(chat?.messages)}
 async function send(){const message=text.trim();if(!message||loading||sendingRef.current||!chat)return;sendingRef.current=true;const controller=new AbortController();setStreamController(controller);const next=[...chat.messages,{role:"user",content:message},{role:"assistant",content:""}];update(next);setText("");setLoading(true);try{const r=await apiFetch(API+"/api/v1/chat/stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,session_id:active,attachment_paths:attachments.map(a=>a.path),web_search:webSearch,memory}),signal:controller.signal});if(!r.ok){update([...next.slice(0,-1),{role:"user",content:message},{role:"assistant",content:await responseDetail(r,"Request failed.")}]);return}if(!r.body)throw new Error("Streaming response unavailable.");const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="",answer="";const handle=(type,p)=>{if(type==="error")throw new Error(p.detail||"Streaming failed.");if(p.text){answer+=p.text;update([...next.slice(0,-1),{role:"user",content:message},{role:"assistant",content:answer}])}};while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split("\n\n");buffer=events.pop()||"";for(const event of events)if(event.trim())parseSSEEvent(event,handle)}buffer+=decoder.decode();if(buffer.trim())parseSSEEvent(buffer,handle);if(!answer)update([...next.slice(0,-1),{role:"user",content:message},{role:"assistant",content:"No response received."}])}catch(e){if(e.name!=="AbortError")update([...next.slice(0,-1),{role:"user",content:message},{role:"assistant",content:e.message||"Streaming failed."}])}finally{sendingRef.current=false;setLoading(false);setStreamController(null);setAttachments([])}}
 function stopStream(){if(!sendingRef.current)return;streamController?.abort();sendingRef.current=false;setStreamController(null);setLoading(false)}
 function newChat(){const id="web-"+Date.now();setChats(cs=>[{id,title:"New conversation",messages:[]},...cs]);setActive(id);setAttachments([]);if(window.innerWidth<701)window.dispatchEvent(new Event("chat:new"))}
 return {chat,update,regenerate,editLastUser,send,stopStream,newChat};
}