import React,{useEffect,useState} from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {createRoot} from "react-dom/client";
import {Menu,Plus,Search,Settings,User,Send,MessageSquare,Paperclip,Files,Trash2,Download,X,Copy,Check} from "lucide-react";
import FileUpload from "./components/FileUpload";
import Modal from "./components/Modal";
import useChat from "./hooks/useChat";
import useFiles from "./hooks/useFiles";
import useMemory from "./hooks/useMemory";
import useMCP from "./hooks/useMCP";
import "./styles.css";

const API=import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";
const initial=[{id:"new",title:"New conversation",messages:[]}];

function App(){
 const [chats,setChats]=useState(initial),[active,setActive]=useState("new"),[text,setText]=useState(""),[loading,setLoading]=useState(false),[sidebar,setSidebar]=useState(true),[settings,setSettings]=useState(false),[filesOpen,setFilesOpen]=useState(false),[fileQuery,setFileQuery]=useState(""),[user,setUser]=useState(null),[auth,setAuth]=useState({email:"",password:"",name:""}),[authMode,setAuthMode]=useState("login"),[attachments,setAttachments]=useState([]),[chatQuery,setChatQuery]=useState(""),[copiedMessage,setCopiedMessage]=useState(null),[memoryOpen,setMemoryOpen]=useState(false),[toast,setToast]=useState(null),[confirmState,setConfirmState]=useState(null),[editState,setEditState]=useState(null),[renameState,setRenameState]=useState(null);
 const token=localStorage.getItem("personal_ai_token");
 function notify(message,type="error"){setToast({message,type});window.clearTimeout(notify.timer);notify.timer=window.setTimeout(()=>setToast(null),3200)}

 useEffect(()=>{if(!token)return;fetch(API+"/api/v1/auth/me",{headers:{Authorization:"Bearer "+token}}).then(async r=>{if(r.ok)setUser((await r.json()).user);else{localStorage.removeItem("personal_ai_token");setUser(null)}}).catch(()=>{});},[token]);
 useEffect(()=>{if(!token||!user)return;fetch(API+"/api/v1/chats",{headers:{Authorization:"Bearer "+token}}).then(async r=>{if(!r.ok)return;const d=await r.json();if(d.chats?.length){const normalized=d.chats.map(c=>({...c,id:c.session_id}));setChats(normalized);setActive(normalized[0].id)}}).catch(()=>{});},[token,user]);
 useEffect(()=>{if(!token||!user||!active||active==="new")return;let cancelled=false;fetch(API+"/api/v1/chats/"+encodeURIComponent(active),{headers:{Authorization:"Bearer "+token}}).then(async r=>{if(!r.ok)return;const d=await r.json();if(cancelled)return;setChats(cs=>cs.map(c=>c.id===active?{...c,messages:d.messages||[]}:c));}).catch(()=>{});return()=>{cancelled=true}},[active,token,user]);

 useEffect(()=>{if(user){loadFiles();loadConnectors();loadMemories()}},[user]);
 const {chat,update,regenerate,editLastUser,send,stopStream,newChat}=useChat({API,token,chats,setChats,active,setActive,text,setText,attachments,setAttachments,loading,setLoading,notify});
 const {files,uploading,loadFiles,uploadFile,deleteFile,confirmDeleteFile,downloadFile}=useFiles({API,token,notify,setAttachments});
 const {memories,memoryForm,setMemoryForm,loadMemories,saveMemory,deleteMemory}=useMemory({API,token,notify});
 const {connectors,connectorForm,setConnectorForm,connectorLoading,loadConnectors,addConnector,deleteConnectorById}=useMCP({API,token,notify});




 async function logout(){try{if(token)await fetch(API+"/api/v1/auth/logout",{method:"POST",headers:{Authorization:"Bearer "+token}})}catch(e){}localStorage.removeItem("personal_ai_token");setUser(null);setChats(initial);setActive("new");}
 async function authSubmit(){const path=authMode==="login"?"/api/v1/auth/login":"/api/v1/auth/register";const body=authMode==="login"?{email:auth.email,password:auth.password}:auth;const r=await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){notify(d.detail||"Authentication failed");return}localStorage.setItem("personal_ai_token",d.token);setUser(d.user);}
 function copyMessage(content,index){try{navigator.clipboard.writeText(content);setCopiedMessage(index);setTimeout(()=>setCopiedMessage(null),1500)}catch(e){}}
 async function renameChat(id,currentTitle){setRenameState({id,value:currentTitle});}
 async function submitRename(){
  const {id,value}=renameState||{};const title=value?.trim();
  if(!id||!title){notify("Chat name cannot be empty");return}
  if(title===chats.find(c=>c.id===id)?.title){setRenameState(null);return}
  const r=await fetch(API+"/api/v1/chats/"+encodeURIComponent(id),{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({title})});
  if(r.ok){setChats(cs=>cs.map(c=>c.id===id?{...c,title}:c));setRenameState(null)}else notify("Rename failed");
 }
 function deleteChatById(id){setConfirmState({type:"chat",id,message:"Delete this conversation?"});}
 async function confirmDeleteChat(id){
  const r=await fetch(API+"/api/v1/chats/"+encodeURIComponent(id),{method:"DELETE",headers:{Authorization:"Bearer "+token}});
  if(!r.ok){notify("Delete failed");return}
  const remaining=chats.filter(c=>c.id!==id);
  setChats(remaining.length?remaining:[{id:"new",title:"New conversation",messages:[]}]);
  if(active===id)setActive(remaining[0]?.id||"new");
 }
 if(!user&&!token)return <div className="auth-screen"><div className="auth-card"><div className="welcome-logo">✦</div><h1>{authMode==="login"?"Welcome back":"Create account"}</h1>{authMode==="register"&&<input placeholder="Name" value={auth.name} onChange={e=>setAuth({...auth,name:e.target.value})}/>}<input placeholder="Email" type="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/><input placeholder="Password" type="password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/><button className="auth-submit" onClick={authSubmit}>{authMode==="login"?"Login":"Sign up"}</button><button className="auth-switch" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Create an account":"Already have an account? Login"}</button></div></div>;

 return <div className="app">
  {sidebar&&<><div className="sidebar-backdrop" onClick={()=>setSidebar(false)}/><aside className="sidebar"><div className="brand"><div className="logo">✦</div>Personal AI Assistant<button onClick={()=>setSidebar(false)}><X size={18}/></button></div><button className="new" onClick={newChat}><Plus size={18}/>New chat</button><div className="search"><Search size={16}/><input placeholder="Search chats" value={chatQuery} onChange={e=>setChatQuery(e.target.value)}/></div><div className="chat-list">{chats.filter(c=>!chatQuery.trim()||c.title.toLowerCase().includes(chatQuery.toLowerCase())).map(c=><div className={"chat-row "+(c.id===active?"active":"")} key={c.id}><button className="chat" onClick={()=>{setActive(c.id);if(window.innerWidth<701)setSidebar(false)}}><MessageSquare size={16}/><span>{c.title}</span></button><button className="chat-more" title="Rename chat" onClick={()=>renameChat(c.id,c.title)}>✎</button><button className="chat-more" title="Delete chat" onClick={()=>deleteChatById(c.id)}>×</button></div>)}</div><div className="sidebar-bottom"><button onClick={()=>{setFilesOpen(true);loadFiles()}}><Files size={17}/>Files</button><button onClick={()=>{setMemoryOpen(true);loadMemories()}}><User size={17}/>Memory</button><button onClick={()=>setSettings(true)}><Settings size={17}/>Settings</button><button onClick={logout}><User size={17}/>Logout</button></div></aside></>}
  <main className="main"><header>{!sidebar&&<button className="icon" onClick={()=>setSidebar(true)}><Menu size={20}/></button>}<div className="model">Personal AI <b>{user?.name||user?.email}</b></div><button className="avatar" onClick={()=>setSettings(true)}><User size={17}/></button></header>
   <section className="messages">{chat.messages.length===0?<div className="welcome"><div className="welcome-logo">✦</div><h1>How can I help?</h1><p>Your personal AI assistant</p></div>:chat.messages.map((m,i)=><div key={i} className={"bubble "+m.role}><div className="role">{m.role==="user"?"You":"Assistant"}</div><div className="message-content">{m.role==="assistant"?(m.content?<ReactMarkdown remarkPlugins={[remarkGfm]}>{m.content}</ReactMarkdown>:loading&&i===chat.messages.length-1?<div className="typing" aria-label="Assistant is thinking"><i></i><i></i><i></i></div>:null):m.content}</div><div className="message-actions"><button className="icon message-action" title="Copy message" onClick={()=>copyMessage(m.content,i)}>{copiedMessage===i?<Check size={14}/>:<Copy size={14}/>}</button>{i===chat.messages.length-1&&m.role==="assistant"&&<button className="icon message-action" title="Regenerate response" onClick={regenerate}>↻</button>}{i===chat.messages.length-2&&m.role==="user"&&chat.messages.at(-1)?.role==="assistant"&&<button className="icon message-action" title="Edit and resend" onClick={()=>{const edit=editLastUser();if(edit)setEditState(edit)}}>✎</button>}</div></div>)}</section>
   <div className="composer-wrap"><div className="composer"><FileUpload onFile={uploadFile}/><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message your assistant..." disabled={loading}/><button className="send" onClick={loading?stopStream:send} disabled={!loading&&!text.trim()}>{loading?"■":<Send size={18}/>}</button></div>{attachments.length>0&&<div className="attachments">{attachments.map(a=><span className="attachment" key={a.path}><Paperclip size={12}/>{a.name}<button onClick={()=>setAttachments(xs=>xs.filter(x=>x.path!==a.path))}><X size={12}/></button></span>)}</div>}{uploading&&<small className="uploading">Uploading file…</small>}<small>AI can make mistakes. Check important information.</small></div>
  </main>
  {toast&&<div className={"toast "+toast.type}>{toast.message}</div>}
  {confirmState&&<div className="overlay"><div className="confirm-card"><h3>Are you sure?</h3><p>{confirmState.message}</p><div className="modal-actions"><button className="secondary" onClick={()=>setConfirmState(null)}>Cancel</button><button className="danger" onClick={async()=>{const x=confirmState;if(x.type==="chat")await confirmDeleteChat(x.id);else await confirmDeleteFile(x.path);setConfirmState(null)}}>Delete</button></div></div></div>}
  {editState&&<div className="overlay"><div className="confirm-card"><div className="settings-head"><h3>Edit message</h3><button onClick={()=>setEditState(null)}>×</button></div><textarea className="modal-textarea" value={editState.value} onChange={e=>setEditState({...editState,value:e.target.value})}/><div className="modal-actions"><button className="secondary" onClick={()=>setEditState(null)}>Cancel</button><button className="primary" onClick={async()=>{const message=editState.value.trim();if(!message){notify("Message cannot be empty");return}const userIndex=editState.index;setEditState(null);setLoading(true);try{const r=await fetch(API+"/api/v1/chats/"+encodeURIComponent(active)+"/edit",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({message,session_id:active})});const d=await r.json();if(!r.ok){notify(d.detail||"Edit failed");return}update([...chat.messages.slice(0,userIndex),{role:"user",content:message},{role:"assistant",content:d.answer}])}finally{setLoading(false)}}}>Save & resend</button></div></div></div>}
  {renameState&&<div className="overlay"><div className="confirm-card"><div className="settings-head"><h3>Rename chat</h3><button onClick={()=>setRenameState(null)}>×</button></div><input className="modal-input" autoFocus value={renameState.value} onChange={e=>setRenameState({...renameState,value:e.target.value})} onKeyDown={e=>{if(e.key==="Enter")submitRename()}}/><div className="modal-actions"><button className="secondary" onClick={()=>setRenameState(null)}>Cancel</button><button className="primary" onClick={submitRename}>Rename</button></div></div></div>}
  {filesOpen&&<Modal title="Files" onClose={()=>setFilesOpen(false)}><input className="file-search" placeholder="Search files..." value={fileQuery} onChange={e=>setFileQuery(e.target.value)}/>{files.length===0?<p>No uploaded files.</p>:files.filter(f=>f.path.toLowerCase().includes(fileQuery.toLowerCase())).map(f=><div key={f.path} style={{display:"flex",alignItems:"center",gap:8,padding:"9px 0",borderBottom:"1px solid #eee"}}><Files size={16}/><span style={{flex:1,overflow:"hidden",textOverflow:"ellipsis"}}>{f.path}</span><small>{f.rag_indexed?"RAG ✓":"Not indexed"} · {Math.ceil(f.size/1024)} KB</small><button className="icon" onClick={()=>downloadFile(f.path)}><Download size={16}/></button><button className="icon" onClick={()=>deleteFile(f.path)}><Trash2 size={16}/></button></div>)}</Modal>}
  {memoryOpen&&<Modal title="Memory" className="settings-large" onClose={()=>setMemoryOpen(false)}><p>Your saved assistant memories.</p><div className="connector-form"><input placeholder="Remember something..." value={memoryForm} onChange={e=>setMemoryForm(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();saveMemory()}}}/><button className="auth-submit" onClick={saveMemory}>Save memory</button></div><div className="connector-list">{memories.length===0?<p>No saved memories.</p>:memories.map((m,i)=><div className="connector-item" key={i}><div><span>{m}</span></div><button className="chat-more" onClick={()=>deleteMemory(m)}>Delete</button></div>)}</div></Modal>}
  {settings&&<Modal title="Settings" className="settings-large" onClose={()=>setSettings(false)}><p>Signed in as <b>{user?.email}</b></p><p>Model: server-configured Groq model</p><hr/><h3>MCP & Connectors</h3><p className="settings-note">Yahan apna remote MCP server add karo. Abhi HTTP/SSE connectors supported hain.</p><div className="connector-form"><input placeholder="Name (e.g. GitHub)" value={connectorForm.name} onChange={e=>setConnectorForm({...connectorForm,name:e.target.value})}/><select value={connectorForm.transport} onChange={e=>setConnectorForm({...connectorForm,transport:e.target.value})}><option value="streamable-http">Streamable HTTP</option><option value="sse">SSE</option></select><input placeholder="MCP server URL" value={connectorForm.url} onChange={e=>setConnectorForm({...connectorForm,url:e.target.value})}/><input placeholder="Allowed tools (optional, comma separated)" value={connectorForm.allowed_tools} onChange={e=>setConnectorForm({...connectorForm,allowed_tools:e.target.value})}/><button className="auth-submit" onClick={addConnector} disabled={connectorLoading}>{connectorLoading?"Adding...":"Add connector"}</button></div><div className="connector-list">{connectors.length===0?<p>No connectors added.</p>:connectors.map(c=><div className="connector-item" key={c.id}><div><b>{c.name}</b><small>{c.transport} · {c.url}</small></div><button className="chat-more" onClick={()=>deleteConnectorById(c.id)}>Delete</button></div>)}</div></Modal>}
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);